version: '3'
services:
  web:
    build:
        context: ./env
        dockerfile: web.docker
    volumes:
        - ../:/var/www
    ports:
        - ${WEB_PORT:-8080}:80
    links:
        - admin:app
  admin:
    build:
      context: ./env
      dockerfile: app.docker
    ports:
      - ${APP_PORT:-9001}:9000
    volumes:
      - ../:/var/www
    links:
      - database
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: registration
        MYSQL_DATABASE: registration
    ports:
        - 33062:3306
    volumes:
        - mysqldata:/var/lib/mysql
        - ../:/home/database

volumes:
  mysqldata:

